language: rust
cache: cargo
rust:
- stable
- beta
- nightly
os: linux
env: TYPE=default RUST_BACKTRACE=1
matrix:
  include:
    - os: linux
      rust: nightly
      env: TYPE=bench RUST_BACKTRACE=1
      script: cargo bench --features unstable
    - os: linux
      rust: nightly
      env: TYPE=rustfmt RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f rustfmt && cargo fmt -- --write-mode=diff) || exit 0
    - os: linux
      rust: nightly
      env: TYPE=clippy RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f clippy && cargo clippy) || exit 0
